INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    352,'INSUMOS MÉDICOS'    ,237,    9    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    1021,'BOLSOS Y MOCHILAS'    ,694,    19    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    537,'MAQUILLAJE'    ,445,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    585,'DESODORANTES'    ,567,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    632,'PIES SALUDABLES'    ,567,    6    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    639,'JABONES, ESPONJAS Y COLONIAS'    ,567,    8    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    767,'MUJER'    ,694,    3    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    804,'FUNKY FISH'    ,694,    5    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    824,'SAN VALENTÍN'    ,694,    9    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    825,'NAVIDAD'    ,694,    10    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    848,'JUEGOS DE MESA'    ,846,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    853,'PELOTAS'    ,846,    6    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    906,'LIMPIEZA DEL HOGAR'    ,889,    5    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    910,'PERROS'    ,909,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    919,'ACCESORIOS DE PILATES'    ,918,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    923,'MEDIDOR DE GRASA CORPORAL'    ,918,    4    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    924,'PODÓMETRO'    ,918,    5    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    925,'BOLSOS Y MOCHILAS'    ,918,    6    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    999,'JUGUETES DIDÁCTICOS'    ,846,    9    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    1025,'LLAVEROS'    ,694,    20    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    1026,'GORRAS'    ,694,    21    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    223,'SALUD COTIDIANA'    ,12,    3    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    238,'VITAMINAS'    ,237,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    293,'SUMÉDICA'    ,237,    7    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    356,'BEBÉS'    ,355,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    446,'CABELLO'    ,445,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    601,'PROTECCIÓN FEMENINA'    ,567,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    610,'AFEITADO'    ,567,    3    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    651,'PAÑUELOS FACIALES'    ,567,    10    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    652,'GEL ANTIBACTERIAL'    ,567,    11    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    789,'NIÑOS '    ,694,    4    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    840,'LIBROS'    ,694,    16    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    844,'TARJETAS'    ,694,    17    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    845,'GIFTCARDS'    ,694,    18    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    847,'PELUCHES'    ,846,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    892,'PARAGUAS'    ,889,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    962,'REGRESO A CLASES'    ,961,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    272,'SALUD SEXUAL'    ,237,    3    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    278,'INCONTINENCIA'    ,237,    4    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    282,'CLIMATERIO'    ,237,    5    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    287,'DIABETES'    ,237,    6    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    558,'PERFUMES Y COLONIAS'    ,445,    3    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    562,'LENCERÍA'    ,445,    4    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    568,'CUIDADO ORAL'    ,567,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    627,'MANICURE Y PEDICURE'    ,567,    5    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    649,'PAPEL HIGIÉNICO'    ,567,    9    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    736,'HOMBRE'    ,694,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    831,'HALLOWEEN'    ,694,    11    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    833,'FIESTA'    ,694,    13    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    834,'CARNAVAL'    ,694,    14    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    904,'FOSFORERAS'    ,889,    3    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    920,'PESAS'    ,918,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    927,'TECNOLOGÍA'    ,926,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    928,'REVISTAS'    ,926,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    930,'CIGARRILLOS ELECTRÓNICOS'    ,926,    3    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    202,'ALIVIO DEL DOLOR'    ,12,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    254,'DIETA Y NUTRICIÓN'    ,237,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    259,'NATURALES'    ,237,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    325,'PRIMEROS AUXILIOS'    ,237,    8    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    620,'DEPILACIÓN'    ,567,    4    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    636,'REPELENTES'    ,567,    7    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    822,'AGENDAS Y DIRECTORIOS'    ,694,    7    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    890,'PILAS, BATERÍAS Y LINTERNAS'    ,889,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    891,'AMBIENTALES'    ,889,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    905,'PEGA INSTANTÁNEA'    ,889,    4    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    911,'GATOS'    ,909,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    912,'HIGIENE Y SALUD MASCOTA'    ,909,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    931,'RASPADITAS'    ,926,    4    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    204,'GRIPE'    ,12,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    211,'DIGESTIVOS'    ,12,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    435,'FUTURA MAMÁ Y MAMÁ'    ,355,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    489,'CUIDADO DE LA PIEL'    ,445,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    654,'ALIMENTOS'    ,653,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    676,'BEBIDAS'    ,653,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    695,'PORTARETRATOS'    ,694,    0    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    701,'HOGAR Y DECORACIÓN'    ,694,    1    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    818,'ÁLBUMES FOTOGRÁFICOS'    ,694,    6    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    823,'TERMOS'    ,694,    8    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    832,'PLAYA'    ,694,    12    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    835,'EMPAQUE REGALOS'    ,694,    15    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    849,'ROMPECABEZAS'    ,846,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    850,'LIBROS, ARTE Y MANUALIDADES'    ,846,    3    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    851,'JUGUETES DE NIÑA'    ,846,    4    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    852,'JUGUETES DE NIÑO'    ,846,    5    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    854,'ELECTRÓNICOS'    ,846,    7    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    855,'JUGUETES TRADICIONALES'    ,846,    8    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    921,'STEPS'    ,918,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    922,'BALANZAS'    ,918,    3    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    929,'ÁLBUMES Y CROMOS COLECCIONABLES'    ,926,    2    );
INSERT OR REPLACE INTO categories (id, description, product_type_id, categories_order) VALUES(    963,'ESCRITORIO'    ,961,    1    );